### ISSUE TITLE
Swet Compost Recipe Issue (test)

### ISSUE THREAD

**Issue by JonMyDude** [JonMyDude/Aethers-Delight#1]
Recipe Issue for swet compost

![image](https://github.com/JonMyDude/Aethers-Delight/assets/68225410/41053983-8759-4996-8b52-394300ec274f)

![image](https://github.com/JonMyDude/Aethers-Delight/assets/68225410/4e72dfef-e36d-44cc-8027-5e246f2662aa)

**Comment by mifort-github** [comment]
omg
